import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: ["./src/**/*.{ts,tsx,js,jsx,mdx}"],
  theme: {
    extend: {
      colors: {
        // Crimson Fury palette (from frontend design html/crimson_fury/DESIGN.md)
        surface: "#131313",
        "surface-dim": "#131313",
        "surface-bright": "#393939",
        "surface-container-lowest": "#0e0e0e",
        "surface-container-low": "#1c1b1b",
        "surface-container": "#201f1f",
        "surface-container-high": "#2a2a2a",
        "surface-container-highest": "#353534",
        "surface-variant": "#353534",
        "surface-tint": "#ffb4a8",
        background: "#131313",
        "on-background": "#e5e2e1",
        "on-surface": "#e5e2e1",
        "on-surface-variant": "#e9bcb5",
        "inverse-surface": "#e5e2e1",
        "inverse-on-surface": "#313030",
        outline: "#b08781",
        "outline-variant": "#5f3f3a",

        primary: "#ffb4a8",
        "on-primary": "#690000",
        "primary-container": "#e60000",
        "on-primary-container": "#fff7f5",
        "inverse-primary": "#c00000",
        "primary-fixed": "#ffdad4",
        "primary-fixed-dim": "#ffb4a8",
        "on-primary-fixed": "#410000",
        "on-primary-fixed-variant": "#930100",

        secondary: "#ffb5a0",
        "on-secondary": "#601400",
        "secondary-container": "#ff5625",
        "on-secondary-container": "#541100",
        "secondary-fixed": "#ffdbd1",
        "secondary-fixed-dim": "#ffb5a0",
        "on-secondary-fixed": "#3b0900",
        "on-secondary-fixed-variant": "#872000",

        tertiary: "#c6c6c7",
        "on-tertiary": "#2f3131",
        "tertiary-container": "#717272",
        "on-tertiary-container": "#f8f8f8",
        "tertiary-fixed": "#e2e2e2",
        "tertiary-fixed-dim": "#c6c6c7",
        "on-tertiary-fixed": "#1a1c1c",
        "on-tertiary-fixed-variant": "#454747",

        error: "#ffb4ab",
        "on-error": "#690005",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "base-unit": "8px",
        gutter: "16px",
        "stack-sm": "8px",
        "stack-md": "24px",
        "stack-lg": "48px",
        "margin-mobile": "20px",
        "margin-desktop": "40px",
      },
      fontFamily: {
        lexend: ["var(--font-lexend)", "Lexend", "sans-serif"],
        "body-md": ["var(--font-lexend)", "Lexend", "sans-serif"],
        "body-lg": ["var(--font-lexend)", "Lexend", "sans-serif"],
        "headline-md": ["var(--font-lexend)", "Lexend", "sans-serif"],
        "headline-lg": ["var(--font-lexend)", "Lexend", "sans-serif"],
        "display-xl": ["var(--font-lexend)", "Lexend", "sans-serif"],
        "label-bold": ["var(--font-lexend)", "Lexend", "sans-serif"],
      },
      fontSize: {
        "display-xl": ["80px", { lineHeight: "1.0", letterSpacing: "-0.04em", fontWeight: "900" }],
        "headline-lg": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "800" }],
        "headline-md": ["32px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "1.6", letterSpacing: "0", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.5", letterSpacing: "0", fontWeight: "400" }],
        "label-bold": ["14px", { lineHeight: "1.0", letterSpacing: "0.05em", fontWeight: "700" }],
      },
    },
  },
  plugins: [],
};

export default config;
