export type Exercise = {
  id: string;
  name: string;
  muscle_group: string;
  secondary_muscles: string[];
  equipment: string;
  difficulty: "beginner" | "intermediate" | "advanced";
  category: "compound" | "isolation" | "cardio" | "plyometric";
  form_tips: string;
  instructions: string;
  swaps: string[];
  icon: string;
};

export const MUSCLE_GROUPS = [
  "All", "Chest", "Back", "Legs", "Shoulders", "Arms", "Core", "Cardio", "Glutes"
];

export const EQUIPMENT_TYPES = [
  "All", "Barbell", "Dumbbell", "Cable", "Machine", "Bodyweight", "Kettlebell", "Band"
];

export const EXERCISES: Exercise[] = [
  // ── CHEST ──────────────────────────────────────────────────
  { id:"1", name:"Barbell Bench Press", muscle_group:"Chest", secondary_muscles:["Triceps","Front Delts"], equipment:"Barbell", difficulty:"intermediate", category:"compound", icon:"fitness_center", form_tips:"Keep shoulder blades retracted and feet flat. Lower to lower chest, not neck.", instructions:"Lie on bench, grip slightly wider than shoulder width, lower bar to chest under control, press explosively.", swaps:["Dumbbell Bench Press","Smith Machine Press","Push Up"] },
  { id:"2", name:"Incline Dumbbell Press", muscle_group:"Chest", secondary_muscles:["Front Delts","Triceps"], equipment:"Dumbbell", difficulty:"intermediate", category:"compound", icon:"fitness_center", form_tips:"Set bench to 30–45°. Don't flare elbows excessively.", instructions:"Lie on incline bench, press dumbbells from chest level to lockout, control the descent.", swaps:["Incline Barbell Press","Cable Incline Fly","Low-to-High Cable"] },
  { id:"3", name:"Cable Crossover", muscle_group:"Chest", secondary_muscles:["Front Delts"], equipment:"Cable", difficulty:"beginner", category:"isolation", icon:"sports_gymnastics", form_tips:"Slight forward lean. Feel the stretch at full extension.", instructions:"Set cables high, bring handles together in front of chest with slight elbow bend. Squeeze hard at peak.", swaps:["Dumbbell Fly","Pec Deck Machine","Band Crossover"] },
  { id:"4", name:"Dips (Chest Focused)", muscle_group:"Chest", secondary_muscles:["Triceps","Front Delts"], equipment:"Bodyweight", difficulty:"intermediate", category:"compound", icon:"accessibility_new", form_tips:"Lean forward to bias chest. Keep elbows slightly flared.", instructions:"Support on parallel bars, lower until upper arm is parallel, press back up.", swaps:["Decline Bench Press","Machine Chest Press"] },
  { id:"5", name:"Dumbbell Fly", muscle_group:"Chest", secondary_muscles:["Biceps"], equipment:"Dumbbell", difficulty:"beginner", category:"isolation", icon:"fitness_center", form_tips:"Slight elbow bend throughout. Don't go below shoulder level.", instructions:"Lie flat, open arms wide like hugging a tree, bring together at top.", swaps:["Cable Crossover","Pec Deck"] },
  { id:"6", name:"Push Up", muscle_group:"Chest", secondary_muscles:["Triceps","Core"], equipment:"Bodyweight", difficulty:"beginner", category:"compound", icon:"accessibility_new", form_tips:"Straight body line. Don't let hips sag.", instructions:"Hands shoulder width, lower chest to ground, press back up with full range.", swaps:["Bench Press","Machine Chest Press"] },

  // ── BACK ───────────────────────────────────────────────────
  { id:"7", name:"Deadlift", muscle_group:"Back", secondary_muscles:["Glutes","Hamstrings","Traps"], equipment:"Barbell", difficulty:"advanced", category:"compound", icon:"fitness_center", form_tips:"Bar close to body, neutral spine, drive through floor. Don't round lower back.", instructions:"Stand with feet hip width, grip outside legs, hinge at hips, keep bar on shins, extend hips and knees.", swaps:["Romanian Deadlift","Trap Bar Deadlift","Rack Pull"] },
  { id:"8", name:"Pull Up", muscle_group:"Back", secondary_muscles:["Biceps","Rear Delts"], equipment:"Bodyweight", difficulty:"intermediate", category:"compound", icon:"accessibility_new", form_tips:"Full dead hang start. Lead with elbows, not hands.", instructions:"Hang from bar, pull chest to bar, lower under control.", swaps:["Lat Pulldown","Assisted Pull Up","Band Pull Up"] },
  { id:"9", name:"Barbell Row", muscle_group:"Back", secondary_muscles:["Biceps","Rear Delts"], equipment:"Barbell", difficulty:"intermediate", category:"compound", icon:"fitness_center", form_tips:"Hinge at 45°, pull to belly button, retract scapula at top.", instructions:"Hinge forward, pull bar from floor to lower abdomen, squeeze lats.", swaps:["Dumbbell Row","Cable Row","T-Bar Row"] },
  { id:"10", name:"Lat Pulldown", muscle_group:"Back", secondary_muscles:["Biceps"], equipment:"Cable", difficulty:"beginner", category:"compound", icon:"sports_gymnastics", form_tips:"Pull to upper chest, not behind neck. Slight lean back.", instructions:"Grip wide, pull bar to clavicle, hold squeeze, return slowly.", swaps:["Pull Up","Close Grip Pulldown","Straight Arm Pulldown"] },
  { id:"11", name:"Seated Cable Row", muscle_group:"Back", secondary_muscles:["Biceps","Rear Delts"], equipment:"Cable", difficulty:"beginner", category:"compound", icon:"sports_gymnastics", form_tips:"Don't swing. Row to abdomen, not chest.", instructions:"Sit upright, pull handle to abdomen, squeeze shoulder blades together.", swaps:["Dumbbell Row","Chest Supported Row"] },
  { id:"12", name:"Face Pull", muscle_group:"Back", secondary_muscles:["Rear Delts","Rotator Cuff"], equipment:"Cable", difficulty:"beginner", category:"isolation", icon:"sports_gymnastics", form_tips:"Pull to face level, external rotate at end. Elbows above wrists.", instructions:"Set cable at head height, pull rope to face with elbows flared high.", swaps:["Band Pull Apart","Rear Delt Fly"] },

  // ── LEGS ───────────────────────────────────────────────────
  { id:"13", name:"Barbell Squat", muscle_group:"Legs", secondary_muscles:["Glutes","Core","Hamstrings"], equipment:"Barbell", difficulty:"advanced", category:"compound", icon:"fitness_center", form_tips:"Knees track over toes. Chest up, neutral spine. Squat to depth.", instructions:"Bar on upper traps, feet shoulder width, sit back and down, drive through heels to stand.", swaps:["Goblet Squat","Leg Press","Hack Squat"] },
  { id:"14", name:"Romanian Deadlift", muscle_group:"Legs", secondary_muscles:["Glutes","Lower Back"], equipment:"Barbell", difficulty:"intermediate", category:"compound", icon:"fitness_center", form_tips:"Soft knee bend, hinge at hips, bar stays close to legs. Feel hamstring stretch.", instructions:"Hold bar at hips, push hips back, lower bar below knee, return by squeezing glutes.", swaps:["Single Leg RDL","Stiff Leg Deadlift","Good Morning"] },
  { id:"15", name:"Leg Press", muscle_group:"Legs", secondary_muscles:["Glutes"], equipment:"Machine", difficulty:"beginner", category:"compound", icon:"sports_gymnastics", form_tips:"Don't lock knees. Full range of motion.", instructions:"Feet shoulder width on platform, lower until 90°, press back up.", swaps:["Barbell Squat","Hack Squat"] },
  { id:"16", name:"Walking Lunges", muscle_group:"Legs", secondary_muscles:["Glutes","Core"], equipment:"Dumbbell", difficulty:"beginner", category:"compound", icon:"accessibility_new", form_tips:"Keep torso upright. Front knee tracks over toe.", instructions:"Step forward, lower back knee near floor, push off to bring feet together, alternate.", swaps:["Reverse Lunge","Bulgarian Split Squat","Step Up"] },
  { id:"17", name:"Leg Extension", muscle_group:"Legs", secondary_muscles:[], equipment:"Machine", difficulty:"beginner", category:"isolation", icon:"sports_gymnastics", form_tips:"Full extension at top, slow descent. Don't swing.", instructions:"Sit in machine, extend legs to lockout, squeeze quads, lower slowly.", swaps:["Terminal Knee Extension","Wall Sit"] },
  { id:"18", name:"Leg Curl", muscle_group:"Legs", secondary_muscles:[], equipment:"Machine", difficulty:"beginner", category:"isolation", icon:"sports_gymnastics", form_tips:"Don't let hips rise. Full contraction.", instructions:"Lie face down, curl heels to glutes, lower under control.", swaps:["Nordic Curl","Swiss Ball Curl"] },
  { id:"19", name:"Calf Raise", muscle_group:"Legs", secondary_muscles:[], equipment:"Machine", difficulty:"beginner", category:"isolation", icon:"accessibility_new", form_tips:"Full stretch at bottom, pause at top.", instructions:"Stand on edge, raise heels as high as possible, lower below platform.", swaps:["Seated Calf Raise","Donkey Calf Raise"] },
  { id:"20", name:"Hack Squat", muscle_group:"Legs", secondary_muscles:["Glutes"], equipment:"Machine", difficulty:"intermediate", category:"compound", icon:"sports_gymnastics", form_tips:"Feet forward. Go deep.", instructions:"Back against pad, feet on platform, lower until thighs are parallel, drive up.", swaps:["Leg Press","Barbell Squat"] },

  // ── SHOULDERS ──────────────────────────────────────────────
  { id:"21", name:"Overhead Press", muscle_group:"Shoulders", secondary_muscles:["Triceps","Upper Traps"], equipment:"Barbell", difficulty:"intermediate", category:"compound", icon:"fitness_center", form_tips:"Brace core. Press bar overhead in straight path. Don't hyperextend lower back.", instructions:"Stand with bar at shoulder height, press overhead to full lockout, lower under control.", swaps:["Dumbbell Shoulder Press","Arnold Press","Machine Press"] },
  { id:"22", name:"Lateral Raise", muscle_group:"Shoulders", secondary_muscles:[], equipment:"Dumbbell", difficulty:"beginner", category:"isolation", icon:"fitness_center", form_tips:"Slight forward lean. Lead with pinkies. Don't shrug.", instructions:"Raise arms to sides to shoulder height, small pause, lower slowly.", swaps:["Cable Lateral Raise","Band Lateral Raise"] },
  { id:"23", name:"Arnold Press", muscle_group:"Shoulders", secondary_muscles:["Triceps"], equipment:"Dumbbell", difficulty:"intermediate", category:"compound", icon:"fitness_center", form_tips:"Rotate throughout. Full range of motion.", instructions:"Start with palms facing you at chest, rotate outward while pressing overhead.", swaps:["Dumbbell Shoulder Press","Overhead Press"] },
  { id:"24", name:"Rear Delt Fly", muscle_group:"Shoulders", secondary_muscles:["Traps","Rhomboids"], equipment:"Dumbbell", difficulty:"beginner", category:"isolation", icon:"fitness_center", form_tips:"Hinge forward, slight elbow bend, lead with elbows.", instructions:"Bend forward, raise arms to sides, squeeze rear delts.", swaps:["Face Pull","Reverse Pec Deck"] },
  { id:"25", name:"Upright Row", muscle_group:"Shoulders", secondary_muscles:["Traps","Biceps"], equipment:"Barbell", difficulty:"intermediate", category:"compound", icon:"fitness_center", form_tips:"Elbows lead. Don't go above chin. Wide grip reduces impingement risk.", instructions:"Hold bar in front, pull to chin with elbows flared wide.", swaps:["Cable Upright Row","Dumbbell Upright Row"] },

  // ── ARMS ───────────────────────────────────────────────────
  { id:"26", name:"Barbell Curl", muscle_group:"Arms", secondary_muscles:["Brachialis"], equipment:"Barbell", difficulty:"beginner", category:"isolation", icon:"fitness_center", form_tips:"Don't swing elbows forward. Full range of motion.", instructions:"Stand with barbell, curl to shoulder height, lower slowly.", swaps:["Dumbbell Curl","EZ Bar Curl","Cable Curl"] },
  { id:"27", name:"Hammer Curl", muscle_group:"Arms", secondary_muscles:["Brachioradialis"], equipment:"Dumbbell", difficulty:"beginner", category:"isolation", icon:"fitness_center", form_tips:"Neutral grip throughout. No swinging.", instructions:"Hold dumbbells in neutral grip, curl to shoulder, lower slowly.", swaps:["Cross Body Hammer Curl","Rope Hammer Curl"] },
  { id:"28", name:"Skull Crusher", muscle_group:"Arms", secondary_muscles:[], equipment:"Barbell", difficulty:"intermediate", category:"isolation", icon:"fitness_center", form_tips:"Elbows stay fixed. Lower to forehead level.", instructions:"Lie on bench, hold EZ bar above chest, lower toward forehead, extend back up.", swaps:["Cable Tricep Pushdown","Dumbbell Overhead Extension"] },
  { id:"29", name:"Tricep Dips", muscle_group:"Arms", secondary_muscles:["Chest","Shoulders"], equipment:"Bodyweight", difficulty:"beginner", category:"compound", icon:"accessibility_new", form_tips:"Elbows close to body. Don't go too deep.", instructions:"Hands on bench behind, lower until 90° at elbow, press back up.", swaps:["Cable Pushdown","Skull Crusher"] },
  { id:"30", name:"Cable Tricep Pushdown", muscle_group:"Arms", secondary_muscles:[], equipment:"Cable", difficulty:"beginner", category:"isolation", icon:"sports_gymnastics", form_tips:"Elbows fixed at sides. Full lockout at bottom.", instructions:"Push rope or bar down until elbows fully extended, return slowly.", swaps:["Skull Crusher","Tricep Dips"] },

  // ── CORE ───────────────────────────────────────────────────
  { id:"31", name:"Plank", muscle_group:"Core", secondary_muscles:["Shoulders","Glutes"], equipment:"Bodyweight", difficulty:"beginner", category:"isolation", icon:"accessibility_new", form_tips:"Straight line from head to heels. Squeeze everything.", instructions:"Hold push up position on forearms, maintain rigid body, breathe.", swaps:["Ab Wheel Rollout","Dead Bug"] },
  { id:"32", name:"Cable Crunch", muscle_group:"Core", secondary_muscles:[], equipment:"Cable", difficulty:"beginner", category:"isolation", icon:"sports_gymnastics", form_tips:"Round spine at bottom. Don't use hips.", instructions:"Kneel at cable, pull weight down by crunching spine, return slowly.", swaps:["Decline Sit Up","Weighted Crunch"] },
  { id:"33", name:"Ab Wheel Rollout", muscle_group:"Core", secondary_muscles:["Lats","Shoulders"], equipment:"Bodyweight", difficulty:"advanced", category:"isolation", icon:"accessibility_new", form_tips:"Hollow body position. Don't let lower back sag.", instructions:"Kneel with wheel, roll forward until hips nearly extended, pull back with abs.", swaps:["Plank","TRX Fallout"] },
  { id:"34", name:"Hanging Leg Raise", muscle_group:"Core", secondary_muscles:["Hip Flexors"], equipment:"Bodyweight", difficulty:"intermediate", category:"isolation", icon:"accessibility_new", form_tips:"Posterior pelvic tilt at top. Control descent.", instructions:"Hang from bar, raise straight or bent legs to waist height, lower slowly.", swaps:["Captain's Chair Leg Raise","Decline Leg Raise"] },

  // ── GLUTES ─────────────────────────────────────────────────
  { id:"35", name:"Hip Thrust", muscle_group:"Glutes", secondary_muscles:["Hamstrings"], equipment:"Barbell", difficulty:"intermediate", category:"compound", icon:"fitness_center", form_tips:"Drive through heels. Full hip extension at top. Chin tucked.", instructions:"Shoulders on bench, barbell on hips, push hips to ceiling, squeeze glutes hard.", swaps:["Glute Bridge","Cable Kickback","Smith Machine Thrust"] },
  { id:"36", name:"Bulgarian Split Squat", muscle_group:"Glutes", secondary_muscles:["Quads","Hamstrings"], equipment:"Dumbbell", difficulty:"intermediate", category:"compound", icon:"fitness_center", form_tips:"Front foot far enough forward. Vertical shin.", instructions:"Rear foot on bench, lower front leg until knee near floor, drive up through heel.", swaps:["Walking Lunge","Reverse Lunge","Step Up"] },
  { id:"37", name:"Glute Kickback", muscle_group:"Glutes", secondary_muscles:[], equipment:"Cable", difficulty:"beginner", category:"isolation", icon:"sports_gymnastics", form_tips:"Don't hyperextend spine. Squeeze at top.", instructions:"On hands and knees at cable, kick heel back and up, squeeze glute.", swaps:["Hip Thrust","Donkey Kick"] },

  // ── CARDIO ─────────────────────────────────────────────────
  { id:"38", name:"Treadmill Run", muscle_group:"Cardio", secondary_muscles:["Legs","Core"], equipment:"Machine", difficulty:"beginner", category:"cardio", icon:"directions_run", form_tips:"Upright posture. Land mid-foot, not heel.", instructions:"Set incline and speed, maintain steady pace, use arms for balance.", swaps:["Outdoor Run","Rowing Machine","Bike"] },
  { id:"39", name:"Battle Ropes", muscle_group:"Cardio", secondary_muscles:["Shoulders","Arms","Core"], equipment:"Bodyweight", difficulty:"intermediate", category:"cardio", icon:"sports_gymnastics", form_tips:"Hips low. Alternate arm waves or slam together.", instructions:"Hold rope ends, create waves alternately or slam both down simultaneously.", swaps:["Box Jump","Burpee"] },
  { id:"40", name:"Box Jump", muscle_group:"Cardio", secondary_muscles:["Legs","Glutes"], equipment:"Bodyweight", difficulty:"intermediate", category:"plyometric", icon:"accessibility_new", form_tips:"Land softly on full foot. Step down, don't jump down.", instructions:"Stand before box, dip and explode up, land with soft knees on box.", swaps:["Broad Jump","Step Up","Burpee"] },
];
